// <auto-generated />
namespace Lesca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Para_Password_Encripted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Para_Password_Encripted));
        
        string IMigrationMetadata.Id
        {
            get { return "201503040735171_Para_Password_Encripted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
